# Generated by Django 2.2.12 on 2020-07-27 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuid', models.CharField(max_length=10, unique=True, verbose_name='微博uid')),
                ('access_token', models.CharField(max_length=32, verbose_name='权限令牌')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
            options={
                'db_table': 'user_weibo_profile',
            },
        ),
    ]
