# Generated by Django 2.2.12 on 2020-07-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_weiboprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weiboprofile',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
